language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: fKDSrsHKK9SnczugfLKOFKELaSsSU2ulEIdQ1qLIcs4kEJ4hFVvkv539bYARIowF8FKVRCn+kRAfIgzI1F7oIaM0kqt9uJ07VDOPSwq8fB/yb4lDbL4oSKn78YNVA9+baM7xflwFRDpvEyHVU/El+PZ2QEtMI5B3fe/JsxRyQcQXP4z/uyVNowM/lpFr+2T0+0kr+pEXMaB9oKB9IxOl6MF9uKBc6v9Q9J1bPEO8OUb0qmfCPNEmAI+dDFiM3hmb/drKvYjYxDhrciiTtmnAcFy77dKxUE1SOHjMUaQIUFcZ15dmuRcyhqiLoBC0e1lx0MMzs+9iHDWlOW2e8540uwmEc1TQ9mVGCQS1jzswWntgqltVrFsD5Zu57THK5nbijL8abOKgUW9II7j7xkZRElW4FPi1iQEUlnXRgmfQNLK0zns9u4lmtKpTdGULeH2jC0x96vo2UU9nM2P/CHyOTHC4U0xeVn5+T0YMuFJBY3DOPN4ZLeDwMftxbPv0X4kAVxq9CzX4xUMzhH+mrjLYfFIP+VZCrQth0wycMDvSZr5tMUdbLIr8V8+P2gC6BsY6Zl0EPMQV7cBxfiuqqcRNr2qb1lyRRmC6Yliqf35HsrkBgFBCkqw93SdT5eosnd7/94QpljrEG0+tysLAvZtF2QlrHarR2VyE2aLFEa/k1RU=
  app: hot-cold-challenge-1.3.2
  on:
    repo: rusye/hot-cold-challenge-1.3.2
